version: "3.7"

services:
  mariadb:
    image: mariadb:10.4
    ports:
      - "3306:3306"
    volumes:
      - ./mariadb/charset.cnf:/etc/mysql/conf.d/charset.cnf
      - /tmp:/var/lib
      - ./mariadb/datamysql:/var/lib/mysql
    networks:
      - laravel-devkit
    domainname: mariadb
    hostname: mariadb
    env_file:
      - ./.env
    restart: on-failure
  cli:
    build: cli
    volumes:
      - ./../:/var/www/html
      - ./php/php.ini:/usr/local/etc/php/php.ini
      - ~/.ssh/known_hosts:/root/.ssh/known_hosts
      - ${SSH_AUTH_SOCK}:/ssh-auth.sock
    user: www-data
    working_dir: /var/www/html
    networks:
      - laravel-devkit
    env_file:
      - ./.env
  http:
    build: http
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./../:/var/www/html
      - ./php/php.ini:/usr/local/etc/php/php.ini
      - ./http/conf/000-default.conf:/etc/apache2/sites-available/000-default.conf
    networks:
      laravel-devkit:
        aliases:
          - laravel.local
    env_file:
      - ./.env

networks:
  laravel-devkit:
    driver: bridge
